### ISSUE TITLE
confRev updated incorrectly on SampledValue Control Block

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#102]
We think the `confRev` is not being correctly updated on some control block types.

For instance in SV control blocks, an update of the `smvID` should not result in a change to `confRev`:

![image](https://github.com/user-attachments/assets/709f2da9-76f0-4384-b490-4be34577ed47)

However we update this on almost any change:

https://github.com/OpenEnergyTools/scl-lib/blob/bd020d3a5534ec9da2915c5f1c7ff5518214b9d6/tSampledValueControl/updateSampledValueControl.ts#L9-L78

Unless there is a TISSUE clarifying this, I think this may need to be changed for GOOSE, SV and maybe also ReportControl blocks.

I'll be happy to prepare a PR.

**Comment by danyill** [comment]
Looking at this a little more closely I think L75 could be included in the preceding `if` block (i.e. between L72 and L73) and this would be sufficient.

**Comment by JakobVogelsang** [comment]
Thank you for the hint. I will make an update here.
