### ISSUE TITLE
Update confRev on dataset removal from control block

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#103]
What we do is on removal of a dataset we sent `confRev` to 0.

https://github.com/OpenEnergyTools/scl-lib/blob/bd020d3a5534ec9da2915c5f1c7ff5518214b9d6/tDataSet/removeDataSet.ts#L14-L34

But I think it should be incremented instead, "inclusive removal of this" in the standard:

![image](https://github.com/user-attachments/assets/6e89b7b5-99f1-4bd2-8bed-7692b19cbec6)

(Background https://github.com/OpenEnergyTools/oscd-publisher/issues/17)

**Comment by JakobVogelsang** [comment]
Yes so true...I will fix this!
