### ISSUE TITLE
(tLN) Remove subscription supervision

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#18]
As a user when I remove a subscription supervision I may want to remove the supervision LN or simply remove the control block reference.

I would like us to have an option for this.

My use case is that I wish to map the supervision instances in an MMS data flow and so as users subscribe and unsubscribe the only thing which changes is the control block reference.

**Comment by danyill** [comment]
The current state is:

* If the supervision LN is made in OpenSCD we remove the whole LN
* Otherwise we remove the DOI.

I'm not sure this is as compliant with IEC 61850-7-1 Ed 2.1 section G.3 as it could be which states:

> When deleting a GOOSE/SMV subscription, the ICT/SCT may either delete the
corresponding LGOS/LSVS instance or update the reference to the source control block
by making it empty, which means that the LGOS/LSVS instance does not supervise any
telegram. 

Updating the reference sounds to me like changing the control block reference to an empty string (i.e. setting `textContent` to an empty string in the `Val` element). It doesn't sound like removing the entire DOI which may have side effects (e.g. loss of descriptions or other metadata). Is there any way we can clarify the intent here? I don't see any relevant TISSUES...

**Comment by danyill** [comment]
@JakobVogelsang how do you understand "update the reference to the source control block by making it empty"?

Should we:

* Remove Val textContent, replace with an empty string (perhaps my interpretation of the standard)
* Remove Val
* Remove DAI
* Remove DOI (current behaviour)
* Remove LN (also allowed in the standard and not only for OpenSCD created elements)

I don't like the use of the DOI/DAI because it may remove other information (e.g. descriptions). For an IED with a fixed data model I think we should ideally be only removing the `<Val>` element or its `textContent`

Can we specify the behaviour more tightly? 

Should we provide the user with an options object:

```ts
type subscriptionRemovalOptions = {
  removalStrategy: "LN" | "DOI" | "DAI" | "Val" | "content";
};

/** Removes subscription supervision - `LGOS` or `LSVS` - when no other data
 * of a given `GSEControl` or `SampledValueControl`
 * @param extRefs - An array of external reference elements
 * @returns Actions to remove subscription supervision `LGOS` or `LSVS`
 */
export function removeSubscriptionSupervision(
  extRefs: Element[],
  options: subscriptionRemovalOptions = { removalStrategy: "DOI" }
): Remove[] {
```

However this paints with a very broad brush or forces the end user to do a "per-ExtRef" event.

What if I want this to adapt to different manufacturers or give end-user control? Perhaps this would be a bad idea, but something like this?

```ts

type removalStrategyOpt = "content" | "Val" | "DAI" | "DOI";

type subscriptionRemovalOptions = {
  removalStrategy: (extRefs: Element[]) => removalStrategyOpt[];
};

/** Removes subscription supervision - `LGOS` or `LSVS` - when no other data
 * of a given `GSEControl` or `SampledValueControl`
 * @param extRefs - An array of external reference elements
 * @returns Actions to remove subscription supervision `LGOS` or `LSVS`
 */
export function removeSubscriptionSupervision(
  extRefs: Element[],
  options: subscriptionRemovalOptions = {
    removalStrategy: (extRefs: Element[]) => extRefs.map(() => "DOI")
  }
): Remove[] {
```

**Comment by JakobVogelsang** [comment]
I would propose to make complex only in request. The current behavior is not good, and I would propose to start and change it to option 1 in your list. Remove subscription supervision by setting the text content of `Val` to empty string.

I cannot imagine this to be conflicting with different vendors, or at least not because of this decision. When this'll pop up in the future, we can still adopt.

Or do you have a case where we need this option already right now. Would this solve issues you have with your vendors?

**Comment by danyill** [comment]
@JakobVogelsang and I discussed and we agreed that the following public API is one useful option for supervisions:

```ts
canRemoveSubscriptionSupervision(lN: Element, options = {removeLn: false}): boolean
removeSubscriptionSupervision(lN: Element, options = {removeLn: false}): Remove[]
```

It differs from the work Jakob is doing for subscription supervision which is targetted at also allowing for multiple subscriptions at the same time and allowing automation where functions receive and returns Edits (and need to track states before the document is acted upon) and suits the granular API I would like for the (upcoming) supervision editor.

`canRemoveSubscriptionSupervision` checks that:

* for any modifications either the DataTypeTemplates support editing (on the `DA`, `setSrcRef` inside the `DOType`) or the first (in the document) LGOS/LSVS has `valImport=true` and `valKind=RO` or `valKind=Conf` (on the `DAI`, `setSrcRef`)
* if `removeLn = true` then that the LN is not the first in the document.
* _it does not_ check e.g. that there are no ExtRefs which use the referenced control block.

`removeSubscriptionSupervision`:

* removes the control block reference (the text content of the Val element) by default
* removes the whole LN if `removeLn=true` and it is allowed

**Comment by danyill** [comment]
@JakobVogelsang I think I'm almost ready to have another go at this unless you'd like to?

**Comment by JakobVogelsang** [comment]
@danyill I am sooo sorry, but I need to have more refinement on this one as well. I feel what you need here as well is an extra function as described above. I would not want to call it `removeSubscriptionSupervision` though because you do not want to input a subscription, but you want to rather `removeSupervision` as you know the supervision logical node. I would therefore propose this:

`function removeSupervision (supervisionLn:Element)`

What is a bit unclear to me is whether you need to have a check before you remove the supervision, and what is it that you want to check upfront?

**Comment by JakobVogelsang** [comment]
Sorry again for this time-consuming refinement process :(

**Comment by danyill** [comment]
I guess to remove we need to check valImport/valKind

We might also (optionally) disallow removal if there is still a subscription to the control block existing? Then for large scale removals they would "naturally" be removed when the last ExtRef subscription was removed.

WDYT?
