### ISSUE TITLE
Consider separating supervision changes from subscription

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#2]
Currently the unsubscribe function removes a supervision instance if possible (last use of it)

https://github.com/OpenEnergyTools/scl-lib/blob/120c39afe14b868dc33d78d30a8cb6bc101f6ff7/tExtRef/unsubscribe.ts#L51-L55

I'd like to separate this.
In my subscriber plugin I've provided a user setting to allow supervision changes not to be made.

My intent is to allow the user to say "I will separately manager and configure supervisions". 

Several tools allow management of supervisions separately from subscribing and unsubscribing and I think we should give the user a choice. 

For example

* In DIGSI 5 supervisions are created separately from their use and if they are not used by an ExtRef they are not automatically removed.
* In SEL Architect, supervisions are created automatically but can also be manually added or removed.

I propose that we pass a boolean to flag to control this.

If we are concerned that this will result in invalid SCL then the other option is to say that the only change which should be made to supervision elements is to blank the `Val` attribute for LGOS and LSVS.

At least for my company we would like to be able to use fixed LGOS and LSVS LN references in DataSets used for MMS and so we prefer not to have "too much automatic fixup". Removing LGOS and LSVS LNs means that user facing information we want to keep (for instance `desc` parameters) would be lost and the user would need an external data source to reallocate them.

I would be happy to do a PR for this if we can agree on requirements.

**Comment by JakobVogelsang** [comment]
added with 0.0.6-rc1
