### ISSUE TITLE
(tLN) (tControl) Instantiate Supervision

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#20]
We currently have:

```ts
/**
 * Returns an array with a single Insert Edit to create a new
 * supervision element for the given GOOSE/SMV message and subscriber IED.
 *
 * @param controlBlock The GOOSE or SMV message element
 * @param subscriberIED The subscriber IED
 * @returns an empty array if instantiation is not possible or an array with a single Create action
 */
export function instantiateSubscriptionSupervision(
  controlBlock: Element | undefined,
  subscriberIED: Element | undefined
): Insert[] {
  const supervisionType =
    controlBlock?.tagName === 'GSEControl' ? 'LGOS' : 'LSVS';
  if (
    !controlBlock ||
    !subscriberIED ||
    !isSupervisionAllowed(controlBlock, subscriberIED, supervisionType)
  )
    return [];
  const availableLN = findOrCreateAvailableLNInst(
    controlBlock,
    subscriberIED,
    supervisionType
  );
  if (
    !availableLN ||
    !isSupervisionModificationAllowed(subscriberIED, supervisionType)
  )
    return [];

  const edits: Insert[] = [];
  // If creating new LN element
  if (!availableLN.parentElement) {
    const parent = subscriberIED.querySelector(
      `LN[lnClass="${supervisionType}"]`
    )?.parentElement;
    if (parent) {
      // use Insert edit for supervision LN
      edits.push({
        parent,
        node: availableLN,
        reference:
          parent!.querySelector(`LN[lnClass="${supervisionType}"]:last-child`)
            ?.nextElementSibling ?? null,
      });
    }
  }

  // Insert child elements
  const supervisionName = supervisionType === 'LGOS' ? 'GoCBRef' : 'SvCBRef';

  let doiElement = availableLN.querySelector(`DOI[name="${supervisionName}"]`);
  if (!doiElement) {
    doiElement = subscriberIED.ownerDocument.createElementNS(
      SCL_NAMESPACE,
      'DOI'
    );
    doiElement.setAttribute('name', supervisionName);
    edits.push({
      parent: availableLN!,
      reference: null,
      node: doiElement,
    });
  }

  let daiElement = doiElement.querySelector(`DAI[name="setSrcRef"]`);
  if (!daiElement) {
    daiElement = subscriberIED.ownerDocument.createElementNS(
      SCL_NAMESPACE,
      'DAI'
    );
    const srcValRef = subscriberIED.querySelector(
      `LN[lnClass="${supervisionType}"]>DOI[name="${supervisionName}"]>DAI[name="setSrcRef"]`
    );
    daiElement.setAttribute('name', 'setSrcRef');

    // transfer valKind and valImport from first supervision instance if present
    if (srcValRef?.hasAttribute('valKind'))
      daiElement.setAttribute('valKind', srcValRef.getAttribute('valKind')!);
    if (srcValRef?.hasAttribute('valImport'))
      daiElement.setAttribute(
        'valImport',
        srcValRef.getAttribute('valImport')!
      );
    edits.push({
      parent: doiElement!,
      reference: null,
      node: daiElement,
    });
  }

  const valTextContent = controlBlockReference(controlBlock);
  let valElement = daiElement.querySelector(`Val`);
  if (!valElement) {
    valElement = subscriberIED.ownerDocument.createElementNS(
      SCL_NAMESPACE,
      'Val'
    );
    valElement.textContent = valTextContent;

    edits.push({
      parent: daiElement!,
      reference: null,
      node: valElement,
    });
  } else {
    edits.push({
      parent: valElement!,
      reference: null,
      node: new Text(valTextContent ?? 'Unknown Control Block'),
    });
  }

  return edits;
}
```

However, this doesn't provide fine grained control and perhaps we could improve this API.

As a user of this function I may want to sometimes instantiate against a new supervision node (even if a supervision is empty the user may not want it to be used, it may be "reserved" for another purpose).

I may also want to specify the supervision instance (?) that I want this to be instantiated against in some cases (is this sane? Perhaps there are many ways a supervision instance could be specified...).

**Comment by JakobVogelsang** [comment]
I would propose a more general function like so:

```ts
instantiateSubscriptionSupervisions(extRefActions: (Insert | Update)[]): Insert[]
```

The reason I would love to have that is:
- allow to be used within multi subscribe sessions. That might be necessary with subscribing to a whole `GSEControl`  or `SampleValueControl`
- such a function could be used in automation processes where you cannot wait for an editor action to do their work 
- the input should be a declaration of intent wherever possible, and I think this is the case here

@danyill my question to you would be: Is it an extra effort to construct such a declaration of intent. I have the feeling that you might want to use it for the subscription supervision plugin, where there is not necessary a subscription happening. Is that true?

**Comment by JakobVogelsang** [comment]
Maybe we need two different functions here :)

**Comment by danyill** [comment]
I like the idea of keeping the API high-level where possible.

Perhaps multiple functions are required - a more granular approach and then an approach more amenable to automation like you propose. 

But I wonder if some workflows just might not work with full automation as there is no way to declare one's intent "I want this subscription to be supervised in this way" in our current API, so we "can't fully express ourselves". I'm not sure what that intent might look like?

* I want supervision instance number X to line up with control block Y
* I want supervision instances to be ordered by IED
* I want to provide a mapping from the control name or other parameter so I can say these control blocks or datasets should use these supervision instances?

And yes,  I would like to use it in a subscription supervision but I really do think that in principle supervisions and subscriptions can be separated (with the only restriction we might have is that a subscription is necessary to carry out a supervision?).

I quite like the way DIGSI 5 does this where you have the freedom to choose your workflow. For some users it may be annoying to have the subscriber plugin allocated the supervision instances only for them to have to be disconnected and re-arranged. They might prefer not to consider this during subscription and to do this as separate workflow step. Others might prefer just to carefully order their subscription process and have the supervisions naturally be correct by virtue of a default order.

**Comment by danyill** [comment]
For "auto-supervising" I guess we'd remove and insert the `Val` element if we are not creating a new LN, so something like:

```ts
instantiateSubscriptionSupervisions(extRefActions: (Insert | Update)[]): (Insert|Remove)[]
```

I guess I'd want this kind of API for my [supervision editor](https://danyill.github.io/oscd-supervision/index.deploy.html) because I'm not sure in my :heart_decoration: that "auto-supervising" is the best approach (due to inability to make a clean declaration of intent and my desire to have a fixed meaning of supervision instances).

In this editor:
* we can disconnect a control block from a supervision LN
* we can connect a control block with a supervision LN
* we can connect a control block to a _new_ supervsion LN
* we can create new supervision LNs

![image](https://github.com/OpenEnergyTools/scl-lib/assets/674783/33e231a1-4ed3-4c44-89c3-90a6fb47ff34)

Maybe I want to export something:

```ts
canCreateSupervision(iedOrControlBlockOrExtRef: Element, type?: 'GOOSE'|'SV'): boolean
canModifySupervision(iedOrControlBlockOrLnOrExtRef, type?: 'GOOSE'|'SV'): boolean
createSupervision(iedOrControlBlockOrExtRef[], type?: 'GOOSE'|'SV'): Insert[]
removeSupervision(controlBlockOrLnOrValOrExtRef: Element[]): Remove[]
```

I should be delighted to discuss this some more. It seems I want to have too complicated a call signature...

**Comment by danyill** [comment]
@JakobVogelsang and I discussed and came up with the following granular API:

```ts
instantiateSubscriptionSupervision(iedOrLn: Element, controlBlock: Element, options = {newLN: false, inst: -1 }): (Insert | Replace)[]
createSupervisionNode(ied: Element, supervisionType: "GOOSE" | "SV", options = { fixInst: -1 }): Insert
```

`instantiateSubscriptionSupervision` - can receive either an IED or a supervision `LN`. It will update the `setSrcRef`'s `Val`'s `textContent` to the control block reference (and if necessary create any missing elements of the structure).

Optionally:

* `inst` allows an instance to be specified (defaults to `-1` which means "next in numerical order")
* I don't recall why `newLN: false` is here (was I too :zzz: at the time). I think perhaps we don't want this as we have separate the functionality out into `createSupervisionNode`

`createSupervisionNode` will allow a new `LN` (with `lnClass=LGOS` or `LSVS`) to be created for an IED given a `supervisionType`, optionally allowing an instance to be specified. It creates a barebones `LN` with only `DOI` of `GoCBRef`, with `SetSrcRef` and `Val` and `Val` has an empty `textContent`. An instance can be specified, as before ,`-1` as the default argument means "next" in order.

**Comment by danyill** [comment]
Just reopening as https://github.com/OpenEnergyTools/scl-lib/issues/20#issuecomment-1659124348 is not fully addressed :wink:

**Comment by danyill** [comment]
So I think we need to close this out:

* `createSupervisionNode`
* `canCreateSupervisionNode`

WDYT @JakobVogelsang

**Comment by danyill** [comment]
Can I open this again as per the previous comment?

**Comment by danyill** [comment]
So this has become a bit confused and so I think I'll close and create separate issues.
