### ISSUE TITLE
Error when using this library in another project

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#28]
I can't integrate the current version of scl-lib in my project due to MIME typing checking. I receive the following console error when using scl-lib version 0.1.0 for `nsd.json`

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/json". Strict MIME type checking is enforced for module scripts per HTML spec.

![image](https://github.com/OpenEnergyTools/scl-lib/assets/674783/1d1aa5b5-e55a-405c-87bb-387ba8143522)

**Comment by danyill** [comment]
I think rather than:

```ts
import dataObjects from "../foundation/nsd.json";
```

I think we need something like:

```ts
import dataObjects from "../foundation/nsd.json" assert {type: 'json'};
```

However this may be an experimental feature we are relying on and there may be a better way:

https://blog.bitsrc.io/how-to-import-json-file-as-a-module-e4965295a7b3

**Comment by JakobVogelsang** [comment]
This error appears only in TypeScript project. You can specify that you want to load json files. Maybe this could be a thing for the documentation.

**Comment by danyill** [comment]
I think this error occurs without the the Typescript project too... after all my browser is not running any typescript when it produces the above error (?)

**Comment by danyill** [comment]
However the above is not a good solution because it is not widely supported: 

https://caniuse.com/mdn-javascript_statements_import_import_assertions_type_json

The best approach seems to be to read and parse in the JSON file:

https://www.stefanjudis.com/snippets/how-to-import-json-files-in-es-modules-node-js/#option-1%3A-read-and-parse-json-files-yourself

**Comment by danyill** [comment]
I've tried a few things.

I tried to use fetch and a JSON file. Then in scl-lib we must explicitly incorporate the json file which then appears in an scl-lib build but doesn't appear in my development server for e.g. oscd-subscriber-later-binding (I guess because there is no explicit reference to it).

 It seems to me the easiest way is just to place the JSON object inside a typescript file:

```ts
const nsd: unknown = {
  NamPlt: {
    cdc: "LPL", ... }
export default nsd;
```

and then we can do:

```ts
import dataObjects from "../foundation/nsd.js";
```

Which works well and makes the compiler do the work and is incorporated downstream. I've done a PR for this and I'm not altogether sure what the downsides might be.

**Comment by ca-d** [comment]
@danyill I'm not quite sure I follow why fetching the `json` file doesn't work for you. Is it that you can't find the file because you don't fetch from `new URL('./relative/path/to/nsd.json', import.meta.url)`? If that's the only reason, I suggest sticking with the json file solution, since a pure data format sounds like the simpler solution for fetching pure data (see comment in #30)
