### ISSUE TITLE
tIED: ImportIED Communication section only imports first ConnectedAP

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#44]
I've been gazing upon the code for transferring the `Communication` section of a newly imported IED:

This seems to assume an IED participates only in a single SubNetwork and only has a single ConnectedAP.

However often IEDs participate in both a StationBus and and a Process Bus subnetwork and have multiple ConnectedAPs.

https://github.com/OpenEnergyTools/scl-lib/blob/864bb51c14137a04d70199d9df3d0e83a9531b07/tIED/insertIED.ts#L9C10-L56

Here is an example ICD file:

[XAT_SEL-487E-5_StandardDesign.ICD.zip](https://github.com/OpenEnergyTools/scl-lib/files/12653148/XAT_SEL-487E-5_StandardDesign.ICD.zip)

I opened:  [test_comms.scd.zip](https://github.com/OpenEnergyTools/scl-lib/files/12653177/test_comms.scd.zip) in https://danyill.github.io/oscd-import-templates/index.deploy.html which is a prototype which I'm testing using this library (and may still be the cause of bugs...).

When I saved the file I saw only the first ConnectedAP. It was actually there twice but that will be a separate issue...

**Comment by JakobVogelsang** [comment]
Very true. The look up for existing `ConnectedAP`s should look for all `ConnectedAP` of the given IED.

**Comment by JakobVogelsang** [comment]
Fixed with version 0.5.10

https://github.com/OpenEnergyTools/scl-lib/commit/384df9b3545f1831ca41b58c4e35bde9813d2538
