### ISSUE TITLE
Change root branch to main

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#52]
Most repos in open-scd use `main` in preference to `master`.

This repo is a bit the exception to the rule.

It's convenient to me (who mostly uses the CLI) if we're consistent.

Would you consider changing this?

**Comment by JakobVogelsang** [comment]
I would and want to as well. I would close the open PRs and then do it. It is a dbut tricky to change otherwise.

**Comment by JakobVogelsang** [comment]
I did switch the branch. Please update your local branches.
