### ISSUE TITLE
tIED: Rename IED

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#55]
It would be useful to be able to rename an IED.

Renaming an IED in IEC 61850 is not quite so simple because the IED name is used in a range of references.

**Requirements:**

1. Check for existing name duplication. If so, do nothing.
1. Rename the `name` attribute on the IED. Some IED tools set the `desc` attribute to the IED name as well. We _could_ (but probably should not (?) change it here as well).
1. Iterate through the `Substation` section. Update any `iedName` on any relevant `LNode`.
1. Iterate through the `Communication` section. Update the `iedName` within each `ConnectedAP`
1. Within _other_ IEDs, update:
    1. The `iedName` field of the `KDC` element.
    2. The `iedName` field of all `ExtRef` elements.
    3. The `iedName` field of all `ClientLN` elements.
    4. The text content of `IEDName` elements within `GSEControl` and `SampledValueControl` should be replaced by the IED's name. We could (but probably should not) also consider if the `appId` attribute should have the IED name replaced on it as it is common for the `appId` to be prefixed by the IED name.
    5. The `iedName` attribute of the `Association` element (something I have never seen in the wild).
    6. The supervision logical nodes (LSVS or LGOS) control block reference LN > DOI[name=GoCBRef/SvCBRef] > DAI[name= setsrcRef] > Val and then update the text content of the control block reference which is prefixed with the IED name (however we must be careful about ambiguous references).

Quite optionally and depending on the approach taken, we could look at the way other namespaces are used:

We could replace `sIedName` while we are there for IEC 61860-6-100 on `LNodeSpecNaming` elements with an `sIedName` attribute.

```
<Private type="eIEC61850-6-100">
  <eIEC61850-6-100:LNodeInputs>
  <eIEC61850-6-100:SourceRef desc="CB state" service="GOOSE" source="XAT/220kV/B230/DCB232/CB/XCBR4.Pos.stVal" input="CB state" extRefAddr="" pLN="XCBR" pDO="Pos" pDA="stVal" />
  </eIEC61850-6-100:LNodeInputs>
  <eIEC61850-6-100:LNodeSpecNaming sIedName="XAT_232_P2" sLdInst="CB" sPrefix="" sLnClass="XCBR" sLnInst="4" />
</Private>
```

Currently OpenSCD handles many of these:

https://github.com/openscd/open-scd/blob/a737c4211360d2d93d44d1e89e731ac8e4c873f2/packages/open-scd/src/wizards/foundation/references.ts#L25-L52

But does not handle control block references for LSVS and LGOS, see https://github.com/openscd/open-scd/issues/1224

**Comment by JakobVogelsang** [comment]
Thank you, @danyill. I will take a look at this asap.

**Comment by JakobVogelsang** [comment]
I would leave out the update of not yet available namespaces and would add that later through addition options. Also, I would propose to have the `appId`, `rptId` and `smvId` optionally. I would also propose to stick with the current call like so:

`updateIED(update:Update): Edit[]`

WDYT @danyill

**Comment by danyill** [comment]
That sounds find to me. Regearding nomenclature, I think it should be `updateIEDName` or `updateIedName` as I could imagine `updateIED` being something which bring an IID file back in.

So something like:

`updateIedName(ied:Element): Edit[]`

Did you mean that you would only modify an `Update`? What about the case where I just want to rename an existing IED and no other change is being made?

Yes, the `appId`, `rptId` and `smvId` should definitely be an optional feature and I'm happy with other namespaces being a future development.

**Comment by JakobVogelsang** [comment]
There is some logic to some of the function in `scl-lib` regarding the naming. Those functions have a `diff` against the SCL as an input and return a `diff` against the SCL. They start either with `remove`, `insert` or `update` follows by the SCL element they touch. In this case we want to update the element IED and with update I mean the same thing as the `Update` edit in OpenSCD core means updating the attributes of the element `IED`. 

For the update function you have in mind I then would prefer to call it merge. @danyill WDYT?

**Comment by danyill** [comment]
> There is some logic to some of the function in `scl-lib` regarding the naming. Those functions have a `diff` against the SCL as an input and return a `diff` against the SCL. They start either with `remove`, `insert` or `update` follows by the SCL element they touch. In this case we want to update the element IED and with update I mean the same thing as the `Update` edit in OpenSCD core means updating the attributes of the element `IED`.
> 
> For the update function you have in mind I then would prefer to call it merge. @danyill WDYT?

Sounds fair, thank you for the explanation
