### ISSUE TITLE
tExtRef: Fetch source control block from ExtRef 

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#57]
We currently have the function available to fetch a control block from an Extref.

We already have a function which does this here:

https://github.com/OpenEnergyTools/scl-lib/blob/main/tControl/sourceControlBlock.ts

I'd like to write some tests and export it, WDYT?

I think it should also exist under the `tExtRef` folder rather than `tControl` at that point.

**Comment by JakobVogelsang** [comment]
I am very fine with this. Tests with more edge cases would be great!
