### ISSUE TITLE
(tLN) Data attribute specification

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#7]
For subscriptions and support of pXX types it would be useful to have a function to bring back the common data class and basic type of a data attribute.

This can be also useful to show the basic type and cdc in the UI (I do this in the later binding plugin on hover).

![image](https://github.com/OpenEnergyTools/scl-lib/assets/674783/3a925616-9271-49d1-a168-2c892bb93cbe)

We currently do something like this:

```ts
function dataAttributeSpecification(
  anyLn: Element,
  doName: string,
  daName: string
): { cdc: string | null; bType: string | null } {
  const doc = anyLn.ownerDocument;
  const lNodeType = doc.querySelector(
    `LNodeType[id="${anyLn.getAttribute('lnType')}"]`
  );

  const doNames = doName.split('.');
  let leaf: Element | null | undefined = lNodeType;
  for (const doN of doNames) {
    const dO: Element | null | undefined = leaf?.querySelector(
      `DO[name="${doN}"], SDO[name="${doN}"]`
    );
    leaf = doc.querySelector(`DOType[id="${dO?.getAttribute('type')}"]`);
  }
  if (!leaf || !leaf.getAttribute('cdc')) return { cdc: null, bType: null };

  const cdc = leaf.getAttribute('cdc')!;

  const daNames = daName.split('.');
  for (const daN of daNames) {
    const dA: Element | null | undefined = leaf?.querySelector(
      `DA[name="${daN}"], BDA[name="${daN}"]`
    );
    leaf =
      daNames.indexOf(daN) < daNames.length - 1
        ? doc.querySelector(`DAType[id="${dA?.getAttribute('type')}"]`)
        : dA;
  }
  if (!leaf || !leaf.getAttribute('bType')) return { cdc, bType: null };

  const bType = leaf.getAttribute('bType')!;

  return { bType, cdc };
}
```

Only question being should we make this composable so that a cdc can be brought back separately for a data object? I think the answer is probably.

**Comment by JakobVogelsang** [comment]
I would ask you to wait a bit. I am working on this as part of the `subscribe` function. This function is part of it. Internally, I am planning to do something like 

```ts
type FcdaSpec = {
  cdc: string,
  bType: string | null,
}

fcdaSpecification(fcda: Element): FcdaSpec | null
```

Returns `null` for an invalid fcda or an orphan fcda.  

How does this sound to you?
