### ISSUE TITLE
tExtRef: Match Source Attributes doesn't match srcLNClass correctly

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#85]
This function doesn't appear to correctly match `srcLNClass`. If it is missing it should default to `LLN0`.

I think we need something like:

```js
 extRef.getAttribute("srcLNClass") ?? "LLN0" === srcLNClass
```

https://github.com/OpenEnergyTools/scl-lib/blob/7cbe03ae29c508af819ae57892b84ea73ca42345/tExtRef/matchSrcAttributes.ts#L8-L22

**Comment by danyill** [comment]
I can do a PR for this and add a test at some stage soon.

**Comment by JakobVogelsang** [comment]
Please do 🥳
