### ISSUE TITLE
(tExtRef) API for subscription

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#9]
Jakob asked:

>  The simple API for such a subscribe  function seems to be impossible, if you take the historical changes and the many used cases subscribing is covering. I therefore have come up with something like this:
> 
> ```ts
> function subscribe(options: SubscriberOption[]): (Update | Insert) []
> ```
> 
> where
> 
> ```ts
> SubscriberOption = {sink: Element, source: {fcda: Element, controlBlock?:Element} | Source}
> ```
> 
> and
> 
> ```ts
> Source = {
>  sourceIed: Element;
>  iedName: string;
>  ldInst: string;
>  prefix: string | null;
>  lnClass: string;
>  lnInst: string | null;
>  doName: string;
>  daName: string | null;
>  fc: string;
>  serviceType?: 'Report' | 'GOOSE' | 'SMV' | 'Poll' | null;
>  srcCBName?: string;
>  srcLDInst?: string;
>  srcPrefix?: string | null;
>  srcLNClass?: string;
>  srcLNInst?: string | null;
> }
> ```
> 
> For now transformer is from `{fcda: Element, controlBlock?: Element}` to Source and internally work with this Object and after failing to cover all scenarious I am thinking of allowing to set source through Source and therefore allow a flexible definition. 
> 
> For the user it does mean more transformation work, but there is still good checks and the automated subscription supervision handling in the background.
> 
> There are two cases where fcda is not sufficient. The main used case is specification where there is only data attributes bind to external reference and we also need to have something to allow bind Poll kind of data where an FCDA as the source is also not sufficient enough.
> 
> The main reason I input an SubscriptionOption instead of just three elements is that we need to allow an array of subscription at once. Doing them one after the other and just fire several events would lead to wrong subscription supervision insert. Those would also lead to incorrect checks of already existing ExtRefs and other phenomenos of that sort. We check agains the SCL and with multiple single events there would be an invalid in.between of the SCL.

Thinking out loud a bit and perhaps being a bit shallow? :stuck_out_tongue_winking_eye: 

I think that the propose SubscriptionOption is too complex and suggest we should have separate functions with simpler, end-user oriented call signatures and APIs to ease adoption and educate the user into the "typical possibilities for actions".

How about:

```ts
function subscribe(subscriptionObject[], options?: Options): (Update | Insert) []
```

```ts
type subscriptionObject = {
  extRef: Element
  fcd: Element,
};
```

Here `fcd` could be a DA or a DO?

```ts
type Options = {
  ignoreSupervisions: boolean,
  isPoll: boolean
  isSpecification: boolean
};
```

I think for other requirements we should have different functions or end-user oriented options, perhaps broadly aligned to Table 51 of -6 Ed 2.1, e.g.

* Adapting pTypes (if that is a valid use case for an SCT)
* If using `isPoll` then an option can allow ignoring of the source control block. 
* If carrying out a specification,  `isSpecification` as an option, then the FCDA is "constructed" by the user (perhaps with a separate function) because the FCDA attributes and the ExtRef attributes are identical for this use case I think.

Looking forward to some discussion.

**Comment by JakobVogelsang** [comment]
I would leave the `Source` object out for now from the `subscription` and would say in the doc that we do not support creating an `ExtRef` for specification. If this is really needed by someone, we can add it later. 

The API you have proposed does not cover some edge cases though, and would propos something in between:

```ts
type SubscribeOptions = {
   ignoreSupervision: boolean;
   ....
}

type Connection = {
   sink: Element;
   source: {fcd: Element, controlBlock?: Element};
}

function subscription(connections: Connection[], options:SubscribeOptions): (Insert | Remove)[]

```

**Comment by danyill** [comment]
It occurs to me that one option we may want is a check for the publisher and subscriber are on the same Subnetwork. Perhaps this also belongs in a function which allows checking if the subscription could be successful somewhere. Probably unnecessary for the first version of this though as we are not using at present.
